[Desktop Entry]
Type=X-GNOME-Metatheme
Name=amoslinux-mellow2-purple
Comment=A partially sexual act; when a female (of any species; mostly humanoids) rubs the ears/lobes of a male Ferengi, creating sensual emotions and chemical reactions in the male (and sometimes in the female).
Encoding=UTF-8

[X-GNOME-Metatheme]
Name=amoslinux-mellow2-purple
GtkTheme=amoslinux-mellow2-purple
IconTheme=amoslinux-mellow2-purple
MetacityTheme=amoslinux-mellow2-purple
