[Desktop Entry]
Type=X-GNOME-Metatheme
Name=oomox-international_astronomy_day
Comment=A partially sexual act; when a female (of any species; mostly humanoids) rubs the ears/lobes of a male Ferengi, creating sensual emotions and chemical reactions in the male (and sometimes in the female).
Encoding=UTF-8

[X-GNOME-Metatheme]
Name=oomox-international_astronomy_day
GtkTheme=oomox-international_astronomy_day
IconTheme=oomox-international_astronomy_day
MetacityTheme=oomox-international_astronomy_day
