[Desktop Entry]
Type=X-GNOME-Metatheme
Name=oomox-wallhaven-k716w7_1920x1080
Comment=A partially sexual act; when a female (of any species; mostly humanoids) rubs the ears/lobes of a male Ferengi, creating sensual emotions and chemical reactions in the male (and sometimes in the female).
Encoding=UTF-8

[X-GNOME-Metatheme]
Name=oomox-wallhaven-k716w7_1920x1080
GtkTheme=oomox-wallhaven-k716w7_1920x1080
IconTheme=oomox-wallhaven-k716w7_1920x1080
MetacityTheme=oomox-wallhaven-k716w7_1920x1080
