[Desktop Entry]
Type=X-GNOME-Metatheme
Name=amos-Cyberpunk-future
Comment=A partially sexual act; when a female (of any species; mostly humanoids) rubs the ears/lobes of a male Ferengi, creating sensual emotions and chemical reactions in the male (and sometimes in the female).
Encoding=UTF-8

[X-GNOME-Metatheme]
Name=amos-Cyberpunk-future
GtkTheme=amos-Cyberpunk-future
IconTheme=amos-Cyberpunk-future
MetacityTheme=amos-Cyberpunk-future
